### ISSUE TITLE
ValueError with networkx 2.0

### ISSUE THREAD

**Issue by jkawamoto** [rgmining/fraud-eagle#1]
~~~
Traceback (most recent call last):
  File "tutorial.py", line 25, in <module>
    diff = graph.update()
  File "/Users/junpei/src/github.com/rgmining/fraud-eagle/fraud_eagle/graph.py", line 486, in update
    return max(diffs)
ValueError: max() arg is an empty sequence
~~~

**Comment by jkawamoto** [comment]
In nextworkx 2.0, successors and predecessors of graphs return an iterator instead of a list.
Current code memoizes those iterators and thus the results of second call are different from the first one.
